default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: capim
  password: capim

development:
  <<: *default
  database: capim_dash_development
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

test:
  <<: *default
  database: capim_dash_test
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>